export type IsfCalculateRequest = {
  client_id?: string | null;
  fiscal_year?: string;
  emission_intensity?: {
    scope1_tco2e?: number;
    scope2_tco2e?: number;
    revenue_inr_cr?: number;
    ppp_factor?: number;
    output_quantity?: number;
    output_unit?: string;
  };
  scope3_spend?: {
    purchased_goods_inr?: number;
    capital_goods_inr?: number;
    fuel_energy_inr?: number;
    transport_inr?: number;
    waste_inr?: number;
    travel_inr?: number;
    commuting_inr?: number;
  };
  energy?: {
    electricity_kwh?: number;
    diesel_hsd_litres?: number;
    petrol_ms_litres?: number;
    furnace_oil_litres?: number;
    lpg_kg?: number;
    cng_kg?: number;
    natural_gas_m3?: number;
    solar_kwh?: number;
    wind_kwh?: number;
    biomass_kwh?: number;
    revenue_inr_cr?: number;
  };
  water?: {
    pin_code?: string;
    groundwater_kl?: number;
    surface_water_kl?: number;
    municipal_water_kl?: number;
    rainwater_kl?: number;
    other_water_kl?: number;
    water_discharged_kl?: number;
    discharge_surface_kl?: number;
    discharge_groundwater_kl?: number;
    discharge_seawater_kl?: number;
    discharge_thirdparty_kl?: number;
    discharge_treated_kl?: number;
    water_withdrawal_stressed_kl?: number;
    water_consumption_stressed_kl?: number;
    zid_implemented?: boolean;
  };
  waste_recovery?: {
    total_generated_mt?: number;
    hazardous_waste_mt?: number;
    non_hazardous_waste_mt?: number;
    plastic_waste_mt?: number;
    ewaste_mt?: number;
    biomedical_waste_mt?: number;
    other_waste_mt?: number;
    recycled_mt?: number;
    reused_mt?: number;
    composted_mt?: number;
    coprocessed_mt?: number;
    other_recovery_mt?: number;
    landfill_mt?: number;
    incineration_mt?: number;
    other_disposal_mt?: number;
  };
  air_emissions?: {
    nox_kg?: number;
    sox_kg?: number;
    pm_kg?: number;
    voc_kg?: number;
    pop_kg?: number;
    hap_kg?: number;
    other_air_kg?: number;
  };
  env_disclosure?: {
    is_designated_consumer?: boolean;
    pat_target_toe?: number;
    pat_escerts?: number;
    ghg_reduction_project?: boolean;
    ghg_project_details?: string;
    emissions_avoided_tco2e?: number;
    waste_mgmt_practices?: string;
    haz_plastic_reduction?: string;
    in_eco_sensitive_area?: boolean;
    eco_sensitive_details?: string;
    biodiversity_impact?: string;
    eia_project_name?: string;
    eia_notification?: string;
    eia_external_agency?: boolean;
    eia_public_domain?: boolean;
    env_complaint?: boolean;
    env_noncompliance_details?: string;
  };
  brsr_assessment_id?: string | null;
};

export type IsfSavedInputs = {
  scope1_tco2e?: number;
  scope2_tco2e?: number;
  revenue_inr_cr?: number;
  ppp_factor?: number;
  output_quantity?: number;
  output_unit?: string;
  purchased_goods_inr?: number;
  capital_goods_inr?: number;
  fuel_energy_inr?: number;
  transport_inr?: number;
  waste_inr?: number;
  travel_inr?: number;
  commuting_inr?: number;
  electricity_kwh?: number;
  diesel_hsd_litres?: number;
  petrol_ms_litres?: number;
  furnace_oil_litres?: number;
  lpg_kg?: number;
  cng_kg?: number;
  natural_gas_m3?: number;
  solar_kwh?: number;
  wind_kwh?: number;
  biomass_kwh?: number;
  pin_code?: string;
  groundwater_kl?: number;
  surface_water_kl?: number;
  municipal_water_kl?: number;
  rainwater_kl?: number;
  other_water_kl?: number;
  water_discharged_kl?: number;
  discharge_surface_kl?: number;
  discharge_groundwater_kl?: number;
  discharge_seawater_kl?: number;
  discharge_thirdparty_kl?: number;
  discharge_treated_kl?: number;
  water_withdrawal_stressed_kl?: number;
  water_consumption_stressed_kl?: number;
  zid_implemented?: boolean;
  total_generated_mt?: number;
  hazardous_waste_mt?: number;
  non_hazardous_waste_mt?: number;
  plastic_waste_mt?: number;
  ewaste_mt?: number;
  biomedical_waste_mt?: number;
  other_waste_mt?: number;
  recycled_mt?: number;
  reused_mt?: number;
  composted_mt?: number;
  coprocessed_mt?: number;
  other_recovery_mt?: number;
  landfill_mt?: number;
  incineration_mt?: number;
  other_disposal_mt?: number;
  nox_kg?: number;
  sox_kg?: number;
  pm_kg?: number;
  voc_kg?: number;
  pop_kg?: number;
  hap_kg?: number;
  other_air_kg?: number;
  is_designated_consumer?: boolean;
  pat_target_toe?: number;
  pat_escerts?: number;
  ghg_reduction_project?: boolean;
  ghg_project_details?: string;
  emissions_avoided_tco2e?: number;
  waste_mgmt_practices?: string;
  haz_plastic_reduction?: string;
  in_eco_sensitive_area?: boolean;
  eco_sensitive_details?: string;
  biodiversity_impact?: string;
  eia_project_name?: string;
  eia_notification?: string;
  eia_external_agency?: boolean;
  eia_public_domain?: boolean;
  env_complaint?: boolean;
  env_noncompliance_details?: string;
};

export type IsfCalculationResponse = {
  id: string;
  client_id?: string;
  fiscal_year?: string;
  inputs?: IsfSavedInputs;
  emission_intensity?: {
    total_ghg_tco2e?: number;
    ppp_revenue?: number;
    intensity_revenue?: number;
    intensity_output?: number;
  };
  scope3?: {
    total_tco2e?: number;
    breakdown?: Record<string, number>;
  };
  energy?: {
    total_gj?: number;
    renewable_gj?: number;
    non_renewable_gj?: number;
    renewable_pct?: number;
    intensity_revenue?: number;
  };
  water?: {
    pin_code?: string;
    state?: string;
    stress_level?: string;
    water_stress_flag?: boolean;
    total_water_kl?: number;
    water_consumption_kl?: number;
    negative_consumption?: boolean;
  };
  waste_recovery?: {
    total_generated_mt?: number;
    total_recovered_mt?: number;
    total_disposed_mt?: number;
    recovery_rate_pct?: number;
  };
  air_emissions?: {
    nox_kg?: number;
    sox_kg?: number;
    pm_kg?: number;
    voc_kg?: number;
    pop_kg?: number;
    hap_kg?: number;
    other_air_kg?: number;
  };
  env_disclosure?: {
    is_designated_consumer?: boolean;
    pat_target_toe?: number;
    pat_escerts?: number;
    ghg_reduction_project?: boolean;
    ghg_project_details?: string;
    emissions_avoided_tco2e?: number;
    waste_mgmt_practices?: string;
    haz_plastic_reduction?: string;
    in_eco_sensitive_area?: boolean;
    eco_sensitive_details?: string;
    biodiversity_impact?: string;
    eia_project_name?: string;
    eia_notification?: string;
    eia_external_agency?: boolean;
    eia_public_domain?: boolean;
    env_complaint?: boolean;
    env_noncompliance_details?: string;
  };
  brsr_populated?: boolean;
  created_at?: string;
};

export type IsfClientStatus = {
  client_id: string;
  company_name: string;
  has_calculation: boolean;
  calculation_id?: string;
};

export type IsfHistoryItem = {
  id: string;
  client_id?: string;
  client_company_name?: string;
  fiscal_year?: string;
  scope3_total_tco2e?: number;
  energy_total_gj?: number;
  recovery_rate_pct?: number;
  created_at?: string;
};

export type ConvertResponse = { value: number; from: string; to: string };
