export type PillarId = "E" | "S" | "G";

export type LikertOption = {
  label: string;
  value: 1 | 2 | 3 | 4 | 5;
};

export type LighthouseQuestion = {
  id: string;
  text: string;
  options: LikertOption[];
};

export type LighthouseKpi = {
  id: string;
  label: string;
  pillar: PillarId;
  pillarLabel: string;
  questions: [LighthouseQuestion, LighthouseQuestion];
};

function opts(labels: [string, string, string, string, string]): LikertOption[] {
  return labels.map((label, i) => ({
    label,
    value: (5 - i) as 1 | 2 | 3 | 4 | 5,
  }));
}

export const PILLAR_META: Record<PillarId, { label: string; defaultWeight: number }> = {
  E: { label: "Environmental", defaultWeight: 0.35 },
  S: { label: "Social", defaultWeight: 0.35 },
  G: { label: "Governance", defaultWeight: 0.3 },
};

export const LIGHTHOUSE_KPIS: LighthouseKpi[] = [
  {
    id: "E1",
    label: "Energy & Emissions",
    pillar: "E",
    pillarLabel: "Environmental",
    questions: [
      {
        id: "E1_Q1",
        text: "Do you track your monthly electricity and fuel bills?",
        options: opts([
          "Yes, digitally tracked with targets to reduce",
          "Yes, tracked regularly",
          "Tracked occasionally",
          "Only when bills arrive",
          "No",
        ]),
      },
      {
        id: "E1_Q2",
        text: "Have you taken any steps to reduce energy use (LED lights, solar panels, efficient machinery, etc.)?",
        options: opts([
          "Yes, multiple measures in place with measurable savings",
          "Yes, a few measures adopted",
          "One or two small steps taken",
          "Planning to start",
          "No steps taken",
        ]),
      },
    ],
  },
  {
    id: "E2",
    label: "Water & Waste",
    pillar: "E",
    pillarLabel: "Environmental",
    questions: [
      {
        id: "E2_Q1",
        text: "How do you manage waste generated by your business?",
        options: opts([
          "Segregated, recycled/sold, and minimal landfill",
          "Waste is segregated and partly recycled",
          "Some waste is segregated",
          "All waste goes to municipal collection",
          "No waste management practice",
        ]),
      },
      {
        id: "E2_Q2",
        text: "Do you take steps to reduce water consumption (rainwater harvesting, recycling, etc.)?",
        options: opts([
          "Yes, active water conservation with measurable results",
          "Yes, some measures in place",
          "Aware but limited action",
          "Planning to start",
          "No",
        ]),
      },
    ],
  },
  {
    id: "E3",
    label: "Sustainable Sourcing",
    pillar: "E",
    pillarLabel: "Environmental",
    questions: [
      {
        id: "E3_Q1",
        text: "Do you prefer suppliers or raw materials that are eco-friendly or locally sourced?",
        options: opts([
          "Yes, it's a key criterion in our procurement",
          "Yes, when possible",
          "Sometimes considered",
          "Rarely considered",
          "Not considered",
        ]),
      },
      {
        id: "E3_Q2",
        text: "Do you use any recycled, biodegradable, or sustainable packaging?",
        options: opts([
          "Yes, mostly sustainable packaging",
          "Partially switched to sustainable options",
          "Exploring options",
          "Aware but no action yet",
          "No, only conventional packaging",
        ]),
      },
    ],
  },
  {
    id: "S1",
    label: "Employee Welfare",
    pillar: "S",
    pillarLabel: "Social",
    questions: [
      {
        id: "S1_Q1",
        text: "Do you provide health insurance or ESI coverage for your employees?",
        options: opts([
          "Yes, for all workers including contract staff",
          "Yes, for all permanent employees",
          "For some employees",
          "Only statutory minimum (PF)",
          "No benefits provided",
        ]),
      },
      {
        id: "S1_Q2",
        text: "Do you provide any skill training or safety training to your workers?",
        options: opts([
          "Regular training programs with records maintained",
          "Training provided periodically",
          "Occasional on-the-job training",
          "Only during onboarding",
          "No training provided",
        ]),
      },
    ],
  },
  {
    id: "S2",
    label: "Community & Fair Practices",
    pillar: "S",
    pillarLabel: "Social",
    questions: [
      {
        id: "S2_Q1",
        text: "Do you hire locally or support local vendors/suppliers?",
        options: opts([
          "Yes, actively prioritize local hiring and vendors",
          "Mostly local workforce and suppliers",
          "Mix of local and non-local",
          "Mostly non-local",
          "No preference given",
        ]),
      },
      {
        id: "S2_Q2",
        text: "Do you ensure timely payment to suppliers and fair wages to workers?",
        options: opts([
          "Yes, always on time with documented records",
          "Mostly on time",
          "Sometimes delayed",
          "Frequently delayed",
          "No fixed schedule",
        ]),
      },
    ],
  },
  {
    id: "S3",
    label: "Product & Customer Safety",
    pillar: "S",
    pillarLabel: "Social",
    questions: [
      {
        id: "S3_Q1",
        text: "Do you have any quality certifications (ISO, BIS, FSSAI, etc.)?",
        options: opts([
          "Yes, multiple relevant certifications",
          "Yes, one key certification",
          "Applied / in process",
          "Planning to apply",
          "No certifications",
        ]),
      },
      {
        id: "S3_Q2",
        text: "Do you have a process to handle customer complaints or product returns?",
        options: opts([
          "Yes, formal process with tracking and resolution timelines",
          "Yes, complaints are addressed but informally",
          "Handled case-by-case",
          "Rarely addressed",
          "No process in place",
        ]),
      },
    ],
  },
  {
    id: "G1",
    label: "Business Structure & Compliance",
    pillar: "G",
    pillarLabel: "Governance",
    questions: [
      {
        id: "G1_Q1",
        text: "Is your business registered (Udyam/MSME, GST, Shop & Establishment, etc.)?",
        options: opts([
          "Yes, all applicable registrations up to date",
          "Most registrations in place",
          "Basic registration only (e.g., GST)",
          "Registration in progress",
          "Not registered",
        ]),
      },
      {
        id: "G1_Q2",
        text: "Do you file taxes and maintain financial records regularly?",
        options: opts([
          "Yes, with a CA/accountant and digital records",
          "Yes, filed on time with proper books",
          "Filed but sometimes delayed",
          "Irregular filing",
          "No formal records",
        ]),
      },
    ],
  },
  {
    id: "G2",
    label: "Ethics & Transparency",
    pillar: "G",
    pillarLabel: "Governance",
    questions: [
      {
        id: "G2_Q1",
        text: "Do you maintain written contracts/agreements with suppliers and clients?",
        options: opts([
          "Yes, for all major transactions",
          "For most transactions",
          "Only for large deals",
          "Rarely",
          "No, mostly verbal agreements",
        ]),
      },
      {
        id: "G2_Q2",
        text: "Do you have a way for employees to raise concerns or grievances?",
        options: opts([
          "Yes, a formal process with confidentiality",
          "Yes, open-door policy in practice",
          "Informally, employees can speak up",
          "Not really encouraged",
          "No mechanism exists",
        ]),
      },
    ],
  },
  {
    id: "G3",
    label: "Risk & Continuity",
    pillar: "G",
    pillarLabel: "Governance",
    questions: [
      {
        id: "G3_Q1",
        text: "Do you have insurance coverage for your business (fire, theft, liability, etc.)?",
        options: opts([
          "Yes, comprehensive coverage",
          "Yes, basic coverage",
          "Partial coverage",
          "Planning to get insured",
          "No insurance",
        ]),
      },
      {
        id: "G3_Q2",
        text: "Do you have a backup plan if a key supplier, machine, or person is unavailable?",
        options: opts([
          "Yes, documented contingency plans",
          "Yes, alternate arrangements identified",
          "Somewhat prepared",
          "Would figure it out when it happens",
          "No backup plan",
        ]),
      },
    ],
  },
];

export const TOTAL_QUESTIONS = LIGHTHOUSE_KPIS.length * 2;

export function countAnswered(answers: Record<string, number>): number {
  return LIGHTHOUSE_KPIS.reduce((n, kpi) => {
    const q1 = answers[kpi.questions[0].id];
    const q2 = answers[kpi.questions[1].id];
    return n + (q1 != null ? 1 : 0) + (q2 != null ? 1 : 0);
  }, 0);
}

const QUESTIONS_PER_PILLAR = 6;

export function countAnsweredByPillar(
  answers: Record<string, number>,
): Record<PillarId, { answered: number; total: number }> {
  const out: Record<PillarId, { answered: number; total: number }> = {
    E: { answered: 0, total: QUESTIONS_PER_PILLAR },
    S: { answered: 0, total: QUESTIONS_PER_PILLAR },
    G: { answered: 0, total: QUESTIONS_PER_PILLAR },
  };
  for (const kpi of LIGHTHOUSE_KPIS) {
    const q1 = answers[kpi.questions[0].id];
    const q2 = answers[kpi.questions[1].id];
    if (q1 != null) out[kpi.pillar].answered += 1;
    if (q2 != null) out[kpi.pillar].answered += 1;
  }
  return out;
}
